name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Amazon EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            set -e
            cd /var/www/html/utsawanrapfa # Ganti dengan direktori yang sesuai dengan setupmu
            sudo git fetch origin
            sudo git reset --hard origin/main
            sudo chown -R ec2-user:nginx /var/www/html/utsawanrapfa/ # Sesuaikan dengan user dan group yang
            digunakan
            sudo chmod -R 775 /var/www/html/utsawanrapfa/ # Sesuaikan dengan izin yang kamu inginkan
            sudo systemctl reload nginx
          EOF
        env:
          SSH_PRIVATE_ KEY: ${{ secrets.SSH_PRIVATE_KEY }}
